cargo-features = ["trim-paths"]

[profile.release]
strip = "symbols"
trim-paths = "all"
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"

[workspace]
resolver = "2"
members = [
    "crates/sqlex-common",
    "crates/sqlex-cli",
    "crates/analyzer/sqlex-analyzer",
    "crates/analyzer/sqlex-hybrid-analyzer",
    "crates/analyzer/sqlex-database-analyzer",
    "crates/analyzer/sqlex-static-analyzer",
    "crates/generator/sqlex-generator",
    "crates/generator/sqlex-generator-debug",
    "crates/generator/sqlex-generator-rust",
    "crates/generator/sqlex-generator-go",
    "crates/generator/sqlex-generator-java",
    "crates/sqlex-compiler",
]

[workspace.dependencies]
# Internal Crates
sqlex-analyzer = { path = "crates/analyzer/sqlex-analyzer" }
sqlex-cli = { path = "crates/sqlex-cli" }
sqlex-common = { path = "crates/sqlex-common" }
sqlex-compiler = { path = "crates/sqlex-compiler" }
sqlex-database-analyzer = { path = "crates/analyzer/sqlex-database-analyzer" }
sqlex-hybrid-analyzer = { path = "crates/analyzer/sqlex-hybrid-analyzer" }
sqlex-generator = { path = "crates/generator/sqlex-generator" }
sqlex-generator-debug = { path = "crates/generator/sqlex-generator-debug" }
sqlex-generator-go = { path = "crates/generator/sqlex-generator-go" }
sqlex-generator-java = { path = "crates/generator/sqlex-generator-java" }
sqlex-generator-rust = { path = "crates/generator/sqlex-generator-rust" }
sqlex-static-analyzer = { path = "crates/analyzer/sqlex-static-analyzer" }

# Core
anyhow = "1.0"
async-trait = "0.1"
thiserror = "2.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Async/Runtime
tokio = { version = "1.43", features = ["full"] }
futures = "0.3"

# Database
sqlparser = "0.54"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "macros"] }

# CLI & Utilities
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
simple_logger = "5.0"
notify = "8.2.0"
rand = "0.8"

# Testing
testcontainers = "0.23"

# Container Management
fs2 = "0.4"
libc = "0.2"
