[package]
name = "sqlex-static-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal
sqlex-analyzer = { workspace = true }
sqlex-common = { workspace = true }

# External
async-trait = { workspace = true }
sqlparser = { workspace = true }

[dev-dependencies]
sqlex-database-analyzer = { workspace = true }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
