[package]
name = "sqlex-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal
sqlex-analyzer = { workspace = true }
sqlex-common = { workspace = true }
sqlex-database-analyzer = { workspace = true }
sqlex-generator = { workspace = true }
sqlex-generator-debug = { workspace = true }
sqlex-generator-go = { workspace = true }
sqlex-generator-java = { workspace = true }
sqlex-generator-rust = { workspace = true }
sqlex-generator-script = { workspace = true }
sqlex-hybrid-analyzer = { workspace = true }
sqlex-static-analyzer = { workspace = true }

# External
anyhow = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sqlparser = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
