[package]
name = "sqlex-generator-script"
version = "0.1.0"
edition = "2021"

[dependencies]
rquickjs.workspace = true
heck.workspace = true
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
tokio.workspace = true

sqlex-generator.workspace = true
sqlex-common.workspace = true

[dev-dependencies]
tempfile = "3.0"
