[package]
name = "sqlex-database-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlex-analyzer = { path = "../sqlex-analyzer" }
tokio = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls", "postgres", "mysql", "sqlite"] }
testcontainers = { workspace = true }
async-trait = { workspace = true }
sqlex-common = { version = "0.1.0", path = "../../common" }

[dev-dependencies]
anyhow = { workspace = true }
