name: test

on: push

jobs:
  build-native:
    uses: ./.github/workflows/native.yml

  test:
    needs:
      - build-native

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download linux shared library
        uses: actions/download-artifact@v3
        with:
          name: linux-shared-library
          path: parser/src/main/resources/native/linux/

      - name: Download windows shared library
        uses: actions/download-artifact@v3
        with:
          name: windows-shared-library
          path: parser/src/main/resources/native/windows/

      - name: Download darwin shared library
        uses: actions/download-artifact@v3
        with:
          name: darwin-shared-library
          path: parser/src/main/resources/native/darwin/

      - name: Execute Gradle test
        run: ./gradlew test
